### ISSUE TITLE
Loading GloVe data?

### ISSUE THREAD

**Issue by jmealo** [guenthermi/postgres-word2vec#1]
Kudos on the project!

I stumbled upon [GloVe](https://github.com/stanfordnlp/GloVe) and immediately wanted to know if I could get this type of data loaded into Postgres and found this repo.

I was wondering what data sets you're using and if GloVe or similar are on your radar.

Thanks,
Jeff

**Comment by guenthermi** [comment]
Hi Jeff,
sorry for the late response, you can add GloVe vectors in a text format to the Postgres database with the [vec2database.py](https://github.com/guenthermi/postgres-word2vec/blob/master/index_creation/vec2database.py) script. However, you probably have to add the numbers of vectors (numbers of lines of the file) and the dimensionality of the vectors as the first line in the file.

You can use every word embedding files which is saved with the save_word2vec_format method of gensims [KeyedVectors](https://radimrehurek.com/gensim/models/keyedvectors.html) class in text format.
