### ISSUE TITLE
psycopg2.ProgrammingError: function vec_to_bytea(real[]) does not exist

### ISSUE THREAD

**Issue by jrcdsf** [guenthermi/postgres-word2vec#14]
(base) admin@ifood-Latitude-5490:~/dev/search/postgres-word2vec/index_creation$ python3 vec2database.py config/vecs_config.json
INFO [2019-06-07 16:39:06] : Exexuted DROP TABLE on google_vecs

INFO [2019-06-07 16:39:06] : Created new table google_vecs

Traceback (most recent call last):
  File "vec2database.py", line 136, in <module>
    main(len(sys.argv), sys.argv)
  File "vec2database.py", line 124, in main
    insert_vectors(vec_config.get_value('vec_file_path'), con, cur, vec_config.get_value('table_name'), db_config.get_value('batch_size'), vec_config.get_value('normalized'), logger)
  File "vec2database.py", line 78, in insert_vectors
    cur.executemany("INSERT INTO "+ table_name + " (word,vector) VALUES (%(word)s, vec_to_bytea(%(vector)s::float4[]))", tuple(values))
psycopg2.ProgrammingError: function vec_to_bytea(real[]) does not exist
LINE 1: ...RT INTO google_vecs (word,vector) VALUES ('</s>', vec_to_byt...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by jrcdsf** [comment]
my mistake

**Comment by onratlgn** [comment]
How did you solve it I have the same mistake
